name: 编译luci-app-easytier_op-apk

on:
  workflow_dispatch:

jobs:
 build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: mipsel_24kc
            NAME: ramips_mt7621
            URL: https://downloads.openwrt.org/snapshots/targets/ramips/mt7621/openwrt-sdk-ramips-mt7621_gcc-13.3.0_musl.Linux-x86_64.tar.zst

          - TARGET: mips_24kc
            NAME: ath79_nand
            URL: https://downloads.openwrt.org/snapshots/targets/ath79/nand/openwrt-sdk-ath79-nand_gcc-13.3.0_musl.Linux-x86_64.tar.zst

          - TARGET: x86_64
            NAME: x86_64
            URL: https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst

          - TARGET: i386_pentium4
            NAME: x86_generic
            URL: https://downloads.openwrt.org/snapshots/targets/x86/generic/openwrt-sdk-x86-generic_gcc-13.3.0_musl.Linux-x86_64.tar.zst

          - TARGET: aarch64_generic
            NAME: rockchip_armv8
            URL: https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/openwrt-sdk-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst

          - TARGET: arm_arm1176jzf-s_vfp
            NAME: bcm27xx_bcm2708
            URL: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2708/openwrt-sdk-bcm27xx-bcm2708_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst

          - TARGET: arm_cortex-a15_neon-vfpv4
            NAME: ipq806x_generic
            URL: https://downloads.openwrt.org/snapshots/targets/ipq806x/generic/openwrt-sdk-ipq806x-generic_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst

          - TARGET: arm_cortex-a5_vfpv4
            NAME: at91_sama5
            URL: https://downloads.openwrt.org/snapshots/targets/at91/sama5/openwrt-sdk-at91-sama5_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst

          - TARGET: aarch64_cortex-a72
            NAME: bcm27xx_bcm2711
            URL: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2711/openwrt-sdk-bcm27xx-bcm2711_gcc-13.3.0_musl.Linux-x86_64.tar.zst

          - TARGET: aarch64_cortex-a53
            NAME: mediatek_filogic
            URL: https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/openwrt-sdk-mediatek-filogic_gcc-13.3.0_musl.Linux-x86_64.tar.zst

          - TARGET: arm_cortex-a7_neon-vfpv4
            NAME: ipq40xx_generic
            URL: https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/openwrt-sdk-ipq40xx-generic_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst

          - TARGET: arm_cortex-a7
            NAME: mediatek_mt7629
            URL: https://downloads.openwrt.org/snapshots/targets/mediatek/mt7629/openwrt-sdk-mediatek-mt7629_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst

          - TARGET: arm_cortex-a9
            NAME: bcm53xx_generic
            URL: https://downloads.openwrt.org/snapshots/targets/bcm53xx/generic/openwrt-sdk-bcm53xx-generic_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst

          - TARGET: arm_cortex-a9_vfpv3-d16
            NAME: mvebu_cortexa9
            URL: https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa9/openwrt-sdk-mvebu-cortexa9_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst

          - TARGET: aarch64_cortex-a76
            NAME: bcm27xx_bcm2712
            URL: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2712/openwrt-sdk-bcm27xx-bcm2712_gcc-13.3.0_musl.Linux-x86_64.tar.zst

          #使用其他型号 参考https://downloads.openwrt.org/snapshots/targets 按上述格式添加
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装SDK
        run: |
          wget -qO /opt/sdk.tar.zst ${{ matrix.URL }}
          tar -I zstd -xf /opt/sdk.tar.zst -C /opt
          cp -R ${{ github.workspace }} /opt/luci-app-easytier
          cd /opt/openwrt-sdk*/package
          cp -R /opt/luci-app-easytier .
          cd /opt/openwrt-sdk*
          ./scripts/feeds update -a
          make defconfig
      - name: 开始编译
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          cd /opt/openwrt-sdk*
          make package/luci-app-easytier/compile V=s -j1
          #make package/luci-app-easytier/compile -j1
          cd /opt/openwrt-sdk*/bin/packages/${{ matrix.TARGET }}/base
          mv luci-app-easytier*.apk luci-app-easytier_${{ matrix.TARGET }}_${{ matrix.NAME }}.apk
          mkdir -p /opt/outapk
          cp -rf *.apk /opt/outapk/
          echo "跳过签名验证安装命令： apk add --allow-untrusted luci-app-easytier_${{ matrix.TARGET }}_${{ matrix.NAME }}.apk"
      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-easytier_${{ matrix.TARGET }}_${{ matrix.NAME }}_APK
          path: /opt/outapk/
     
